name: Release BadgerCLI

on:
  push:
    tags:
      - 'v*.*.*-release'

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Build for Linux
        run: GOOS=linux GOARCH=amd64 go build -o badgercli-linux cmd/badgercli/main.go

      - name: Build for macOS
        run: GOOS=darwin GOARCH=amd64 go build -o badgercli-mac cmd/badgercli/main.go

      - name: Build for Windows
        run: GOOS=windows GOARCH=amd64 go build -o badgercli-win.exe cmd/badgercli/main.go

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            badgercli-linux
            badgercli-mac
            badgercli-win.exe
          token: ${{ secrets.PAT_TOKEN }}
